### ISSUE TITLE
i think the det function shoule be rewrited

### ISSUE THREAD

**Issue by ZhouXiaolin** [nicebyte/nicemath#3]
inspire from https://github.com/ssloy/tinyrenderer/blob/master/geometry.h

**Comment by nicebyte** [comment]
the implementation linked above uses the more "human-friendly" definition of determinant, which involves computing determinants recursively. that approach looks like it would be harder for the compiler to optimize. 

the current (less generic) implementation of `det` is likely to be faster though i could be convinced otherwise if shown a benchmark.

i don't use this library for matrices that are larger than 4x4 which is why i never implemented a generic version. if you have a use case that involves larger matrices, i'd be glad to hear it; it's always possible to add the generic function in addition to the ones present right now.

**Comment by nicebyte** [comment]
closing for now, lmk if you have further comments.
